---
default_url: https://pincountpodcast.com/
name: Pincount Podcast
subtitle: No tech too trivial.
summary: Pincount is a tech podcast not afraid of the details. We're experts, not  just users, we're computer scientists and developers. Join us for half an hour each week to get into the detail on new tech and speculate about what might be next.
description: Pincount is a tech podcast not afraid of the details. We're experts, not  just users, we're computer scientists and developers. Join us for half an hour each week to get into the detail on new tech and speculate about what might be next.
copyright: &#x2117; &amp; &#xA9; 2016 Iain Wallace, Douglas Shearer
