---
domain: http://pincountpodcast.com
name:        Pincount Podcast
subtitle:    Going deep into the tech with Iain Wallace and Douglas Shearer.
description: Pincount is a tech podcast not afraid of the details. We're experts, not  just users, we're computer scientists and developers. Join us for half an hour each week to get into the detail on new tech and speculate about what might be next.
authors:     Iain Wallace and Douglas Shearer
keywords:    tech,technology,gadgets,geek,apple,mac,iphone,ipad,ios,development,software,gpu,pc,computer,science

itunes_category:    Technology
itunes_subcategory: Tech News
